# Generated by Django 3.1.2 on 2021-05-19 00:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='カテゴリ名')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='タグ名')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('description', models.CharField(max_length=300, verbose_name='動画説明文')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日')),
                ('edited', models.BooleanField(default=False)),
                ('movie', models.FileField(blank=True, upload_to='tube/movie', verbose_name='動画')),
                ('mime', models.TextField(null=True, verbose_name='MIMEタイプ')),
                ('thumbnail', models.ImageField(null=True, upload_to='tube/thumbnail/', verbose_name='サムネイル')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tube.category', verbose_name='カテゴリ')),
                ('tag', models.ManyToManyField(blank=True, to='tube.Tag', verbose_name='タグ')),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500, verbose_name='コメント文')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.video', verbose_name='コメント先の動画')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
